# Generated by Django 5.0.1 on 2024-02-15 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitio_web', models.TextField()),
                ('email', models.TextField()),
                ('telefono', models.TextField()),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calle', models.TextField()),
                ('ciudad', models.TextField()),
                ('estado', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
            options={
                'db_table': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('imagen', models.TextField()),
                ('nombre', models.TextField()),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosRestaurantes.contactos')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosRestaurantes.direcciones')),
            ],
            options={
                'db_table': 'restaurantes',
            },
        ),
    ]
