# Generated by Django 5.0.1 on 2024-02-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosRestaurantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantes',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='restaurantes',
            name='direccion',
        ),
        migrations.AddField(
            model_name='contactos',
            name='restaurante_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datosRestaurantes.restaurantes'),
        ),
        migrations.AddField(
            model_name='direcciones',
            name='restaurante_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datosRestaurantes.restaurantes'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
