# Generated by Django 5.0.1 on 2024-02-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosRestaurantes', '0002_remove_restaurantes_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='restaurante_id',
            new_name='restaurante',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='restaurante_id',
            new_name='restaurante',
        ),
    ]
